# Generated by Django 4.2.25 on 2025-10-19 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='created_at',
        ),
    ]
